import { EventItem } from "./types";

// Real Jordanian cities with accurate coordinates.
// Summer 2026 sample events across Music, Cultural, Sports, Food.
export const EVENTS: EventItem[] = [
  {
    id: "jerash-festival",
    title: "Jerash Festival of Culture & Arts",
    titleAr: "مهرجان جرش للثقافة والفنون",
    category: "cultural",
    cost: "paid",
    price: 10,
    description:
      "Jordan's flagship summer festival returns to the ancient Roman city of Jerash with music, dance, theatre and poetry from across the Arab world. Performances fill the South Theatre and the colonnaded streets under the stars.",
    descriptionAr:
      "يعود مهرجان الأردن الصيفي الأبرز إلى مدينة جرش الرومانية القديمة بالموسيقى والرقص والمسرح والشعر من أنحاء العالم العربي.",
    city: "Jerash",
    cityAr: "جرش",
    venue: "Jerash Archaeological Site — South Theatre",
    venueAr: "موقع جرش الأثري - المدرج الجنوبي",
    date: "2026-07-22",
    time: "19:00",
    lat: 32.2808,
    lng: 35.8911,
    organizer: "Ministry of Culture",
    accessibility: { wheelchair: true, familyFriendly: true, signLanguage: false },
    cover: "🏛️",
  },
  {
    id: "rainbow-street-night",
    title: "Rainbow Street Summer Night Market",
    titleAr: "سوق ليالي قوس قزح الصيفي",
    category: "food",
    cost: "free",
    description:
      "Amman's beloved Rainbow Street closes to cars for an evening of street food, local makers, live oud, and family fun. Sample knafeh, falafel, and Jordanian sweets from dozens of vendors.",
    descriptionAr:
      "يغلق شارع الرينبو المحبوب أبوابه أمام السيارات لأمسية من طعام الشارع والحرفيين المحليين والعزف الحي والمرح العائلي.",
    city: "Amman",
    cityAr: "عمّان",
    venue: "Rainbow Street, Jabal Amman",
    venueAr: "شارع الرينبو، جبل عمّان",
    date: "2026-06-13",
    time: "18:00",
    lat: 31.9515,
    lng: 35.9239,
    organizer: "Greater Amman Municipality",
    accessibility: { wheelchair: false, familyFriendly: true, signLanguage: false },
    cover: "🍴",
  },
  {
    id: "aqaba-beach-concert",
    title: "Aqaba Beach Sunset Concert",
    titleAr: "حفل غروب شاطئ العقبة",
    category: "music",
    cost: "donation",
    description:
      "A free, donation-based beachfront concert on the Red Sea featuring Jordanian indie and folk bands. Bring a blanket, watch the sun set over the Gulf, and dance on the sand.",
    descriptionAr:
      "حفل موسيقي مجاني قائم على التبرعات على شاطئ البحر الأحمر يضم فرقًا أردنية مستقلة وشعبية.",
    city: "Aqaba",
    cityAr: "العقبة",
    venue: "Aqaba Public Beach",
    venueAr: "شاطئ العقبة العام",
    date: "2026-07-04",
    time: "17:30",
    lat: 29.5267,
    lng: 35.0078,
    organizer: "Aqaba Arts Collective",
    accessibility: { wheelchair: true, familyFriendly: true, signLanguage: false },
    cover: "🎶",
  },
  {
    id: "dead-sea-run",
    title: "Dead Sea Ultra Marathon",
    titleAr: "ماراثون البحر الميت",
    category: "sports",
    cost: "paid",
    price: 25,
    description:
      "Run the lowest road on Earth, descending toward the Dead Sea. Routes for all levels from a family 10K to the full 50K ultra. Proceeds support the Society for the Care of Neurological Patients.",
    descriptionAr:
      "اركض على أخفض طريق على وجه الأرض نحو البحر الميت. مسارات لجميع المستويات من 10 كم عائلي إلى 50 كم.",
    city: "Dead Sea",
    cityAr: "البحر الميت",
    venue: "Amman Beach, Dead Sea Highway",
    venueAr: "شاطئ عمّان، طريق البحر الميت",
    date: "2026-06-27",
    time: "06:00",
    lat: 31.5497,
    lng: 35.5658,
    organizer: "Dead Sea Marathon Committee",
    accessibility: { wheelchair: false, familyFriendly: true, signLanguage: false },
    cover: "🏃",
  },
  {
    id: "amman-citadel-evenings",
    title: "Citadel Heritage Evenings",
    titleAr: "أمسيات قلعة عمّان التراثية",
    category: "cultural",
    cost: "free",
    description:
      "Free guided heritage walks through the Amman Citadel at dusk, with storytellers recounting the city's Roman, Byzantine, and Umayyad past. Panoramic views over downtown at golden hour.",
    descriptionAr:
      "جولات تراثية مجانية بصحبة مرشدين في قلعة عمّان عند الغسق، مع رواة يحكون تاريخ المدينة الروماني والبيزنطي والأموي.",
    city: "Amman",
    cityAr: "عمّان",
    venue: "Amman Citadel (Jabal al-Qal'a)",
    venueAr: "قلعة عمّان (جبل القلعة)",
    date: "2026-06-20",
    time: "18:30",
    lat: 31.9548,
    lng: 35.9344,
    organizer: "Department of Antiquities",
    accessibility: { wheelchair: true, familyFriendly: true, signLanguage: true },
    cover: "🏰",
  },
  {
    id: "irbid-food-fest",
    title: "Irbid Northern Flavors Food Festival",
    titleAr: "مهرجان نكهات الشمال في إربد",
    category: "food",
    cost: "free",
    description:
      "Celebrate northern Jordanian cuisine with free tastings of galayet bandora, freekeh, and homemade dairy from Irbid's farms. Cooking demos and a kids' baking corner all day.",
    descriptionAr:
      "احتفل بالمطبخ الأردني الشمالي مع تذوق مجاني لقلاية البندورة والفريكة ومنتجات الألبان المنزلية من مزارع إربد.",
    city: "Irbid",
    cityAr: "إربد",
    venue: "Irbid Cultural Park",
    venueAr: "حديقة إربد الثقافية",
    date: "2026-08-08",
    time: "16:00",
    lat: 32.5556,
    lng: 35.85,
    organizer: "Irbid Municipality",
    accessibility: { wheelchair: true, familyFriendly: true, signLanguage: false },
    cover: "🥘",
  },
  {
    id: "wadi-rum-stargazing",
    title: "Wadi Rum Desert Stargazing Night",
    titleAr: "ليلة رصد النجوم في وادي رم",
    category: "cultural",
    cost: "donation",
    description:
      "A community stargazing night in the protected desert of Wadi Rum. Bedouin guides share constellation stories over tea and a campfire. Telescopes provided; all ages welcome.",
    descriptionAr:
      "ليلة رصد نجوم مجتمعية في صحراء وادي رم المحمية. يشارك المرشدون البدو قصص الأبراج حول الشاي والنار.",
    city: "Wadi Rum",
    cityAr: "وادي رم",
    venue: "Wadi Rum Protected Area",
    venueAr: "محمية وادي رم",
    date: "2026-07-18",
    time: "20:00",
    lat: 29.5765,
    lng: 35.4204,
    organizer: "Wadi Rum Tourism Cooperative",
    accessibility: { wheelchair: false, familyFriendly: true, signLanguage: false },
    cover: "✨",
  },
  {
    id: "zarqa-youth-football",
    title: "Zarqa Community Football Cup",
    titleAr: "كأس الزرقاء المجتمعي لكرة القدم",
    category: "sports",
    cost: "free",
    description:
      "A free neighborhood football tournament open to all youth teams across Zarqa. Cheer on local squads, with halftime entertainment and free water and snacks for spectators.",
    descriptionAr:
      "بطولة كرة قدم مجانية للأحياء مفتوحة لجميع فرق الشباب في الزرقاء، مع ترفيه في الاستراحة ووجبات خفيفة مجانية.",
    city: "Zarqa",
    cityAr: "الزرقاء",
    venue: "Prince Mohammed Stadium",
    venueAr: "استاد الأمير محمد",
    date: "2026-06-06",
    time: "17:00",
    lat: 32.0608,
    lng: 36.0942,
    organizer: "Zarqa Youth Sports Club",
    accessibility: { wheelchair: true, familyFriendly: true, signLanguage: false },
    cover: "⚽",
  },
  {
    id: "amman-jazz-roof",
    title: "Downtown Amman Rooftop Jazz",
    titleAr: "جاز فوق أسطح وسط عمّان",
    category: "music",
    cost: "paid",
    price: 8,
    description:
      "An intimate rooftop jazz evening overlooking downtown Amman, featuring a trio of Jordanian and regional musicians. Limited seating; light refreshments included.",
    descriptionAr:
      "أمسية جاز حميمة على سطح مطل على وسط عمّان، تضم ثلاثي من الموسيقيين الأردنيين والإقليميين.",
    city: "Amman",
    cityAr: "عمّان",
    venue: "Al-Balad Rooftop, Downtown",
    venueAr: "سطح البلد، وسط البلد",
    date: "2026-07-11",
    time: "20:30",
    lat: 31.9497,
    lng: 35.9328,
    organizer: "Amman Jazz Society",
    accessibility: { wheelchair: false, familyFriendly: false, signLanguage: false },
    cover: "🎷",
  },
  {
    id: "salt-heritage-walk",
    title: "As-Salt Old Town Festival",
    titleAr: "مهرجان مدينة السلط القديمة",
    category: "cultural",
    cost: "free",
    description:
      "Celebrate the UNESCO-listed yellow-stone town of As-Salt with free walking tours, traditional crafts, dabke dancing in the squares, and open historic houses.",
    descriptionAr:
      "احتفل بمدينة السلط الحجرية الصفراء المدرجة في اليونسكو بجولات مشي مجانية وحرف تقليدية ودبكة في الساحات.",
    city: "As-Salt",
    cityAr: "السلط",
    venue: "As-Salt Historic Old Town",
    venueAr: "البلدة القديمة في السلط",
    date: "2026-08-15",
    time: "17:00",
    lat: 32.0392,
    lng: 35.7272,
    organizer: "As-Salt Development Corporation",
    accessibility: { wheelchair: false, familyFriendly: true, signLanguage: true },
    cover: "🏘️",
  },
  {
    id: "madaba-mosaic-fair",
    title: "Madaba Mosaic & Crafts Fair",
    titleAr: "معرض الفسيفساء والحرف في مادبا",
    category: "cultural",
    cost: "free",
    description:
      "Watch master artisans create Madaba's famous mosaics live, with free workshops for kids. Local food stalls and folk music throughout the evening in the city center.",
    descriptionAr:
      "شاهد الحرفيين المهرة وهم يصنعون فسيفساء مادبا الشهيرة مباشرة، مع ورش عمل مجانية للأطفال.",
    city: "Madaba",
    cityAr: "مادبا",
    venue: "Madaba City Center",
    venueAr: "وسط مدينة مادبا",
    date: "2026-07-25",
    time: "18:00",
    lat: 31.7167,
    lng: 35.7933,
    organizer: "Madaba Tourism Board",
    accessibility: { wheelchair: true, familyFriendly: true, signLanguage: false },
    cover: "🎨",
  },
  {
    id: "amman-night-cycle",
    title: "Amman Night Cycling Ride",
    titleAr: "جولة عمّان الليلية بالدراجات",
    category: "sports",
    cost: "free",
    description:
      "A free, family-friendly group bike ride through Amman's quiet evening streets, escorted by volunteers. All bikes welcome; a fun way to see the city after dark.",
    descriptionAr:
      "جولة دراجات جماعية مجانية ومناسبة للعائلات في شوارع عمّان الهادئة مساءً، بمرافقة متطوعين.",
    city: "Amman",
    cityAr: "عمّان",
    venue: "Start: Abdali Boulevard",
    venueAr: "البداية: بوليفارد العبدلي",
    date: "2026-06-19",
    time: "21:00",
    lat: 31.9628,
    lng: 35.9094,
    organizer: "Bike to the Future Jordan",
    accessibility: { wheelchair: false, familyFriendly: true, signLanguage: false },
    cover: "🚲",
  },
];

export function getEventById(id: string): EventItem | undefined {
  return EVENTS.find((e) => e.id === id);
}
